namespace DataAccess.RequestDTOs;

public class GetManyPartnerSupportedLocationsSettingsRequestDTO : AbstractGetManySettingsDTO<PartnerSupportedLocationFiltersRequestDTO, PartnerSupportedLocationSortingRequestDTO>;